# BetterProto stubs for engine.proto
#
# engine.py          — auto-generated by betterproto (messages + grpclib stub)
# grpcio_support.py  — hand-written grpcio adapter (not overwritten by generator)

from .engine import (
    AlarmRecord,
    AnalyzeOnlineAlarmClusterRequest,
    OnlineAlarmClusterReport,
    OnlineAlarmClusterResult,
    AlarmClusteringServiceStub,
)
from .grpcio_support import (
    AlarmClusteringServiceBase,
    add_to_server,
)

__all__ = [
    "AlarmRecord",
    "AnalyzeOnlineAlarmClusterRequest",
    "OnlineAlarmClusterReport",
    "OnlineAlarmClusterResult",
    "AlarmClusteringServiceStub",
    "AlarmClusteringServiceBase",
    "add_to_server",
]
