# Generated by betterproto from proto/engine.proto
# Regenerate with: python generate_betterproto.py
#
# DO NOT EDIT — this file is overwritten each time the generator runs.
#
# BetterProto field-name mapping vs proto source
# ───────────────────────────────────────────────
#   Proto "_source_id"  (field #1) → Python "source_id"   (leading underscore stripped)
#   Proto "requestId"              → Python "request_id"
#   Proto "alarmRecords"           → Python "alarm_records"
#   Proto "alarmType"              → Python "alarm_type"
#   Proto "clusterId"              → Python "cluster_id"
#   Proto "reportType"             → Python "report_type"
#
# gRPC service layer
# ──────────────────
# BetterProto generates AlarmClusteringServiceStub (client) and
# AlarmClusteringServiceBase (server) that target grpclib, not grpcio.
# For a grpcio server, see proto_betterproto/grpcio_support.py.
from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, List, Mapping, Optional, Tuple, Union

import betterproto

if TYPE_CHECKING:
    from grpclib.metadata import Deadline

# grpclib's _MetadataLike inlined to avoid a runtime import
_MetadataLike = Union[Mapping[str, Union[str, bytes]], List[Tuple[str, Union[str, bytes]]]]


# ── Messages ───────────────────────────────────────────────────────────────────

@dataclass
class AlarmRecord(betterproto.Message):
    source_id: str = betterproto.string_field(1)           # proto: _source_id
    managed_objects: str = betterproto.string_field(2)
    alarm_type: str = betterproto.string_field(3)
    probable_cause: str = betterproto.string_field(4)
    perceived_severity: str = betterproto.string_field(5)
    state: str = betterproto.string_field(6)
    created_at: str = betterproto.string_field(7)
    closed_at: str = betterproto.string_field(8)


@dataclass
class AnalyzeOnlineAlarmClusterRequest(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    system: str = betterproto.string_field(2)
    alarm_records: List[AlarmRecord] = betterproto.message_field(3)


@dataclass
class OnlineAlarmClusterResult(betterproto.Message):
    source_id: str = betterproto.string_field(1)           # proto: _source_id
    cluster_id: int = betterproto.int32_field(2)
    confidence: float = betterproto.float_field(3)


@dataclass
class OnlineAlarmClusterReport(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    report_type: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    message: str = betterproto.string_field(4)
    results: List[OnlineAlarmClusterResult] = betterproto.message_field(5)


# ── Client stub (grpclib-based — generated by betterproto) ────────────────────
# Uses grpclib.client.Channel, not grpcio.
# For a grpcio client, import AlarmClusteringServiceStub from grpcio_support.py.

class AlarmClusteringServiceStub(betterproto.ServiceStub):
    async def analyze_online_alarm_cluster(
        self,
        request: AnalyzeOnlineAlarmClusterRequest,
        *,
        timeout: Optional[float] = None,
        deadline: Optional[betterproto.Deadline] = None,
        metadata: Optional[betterproto.MetadataLike] = None,
    ) -> OnlineAlarmClusterReport:
        return await self._unary_unary(
            "/alarm_clustering.AlarmClusteringService/AnalyzeOnlineAlarmCluster",
            request,
            OnlineAlarmClusterReport,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )
