# Generated by betterproto from proto/engine.proto
# Regenerate with: python generate_betterproto.py
#
# Key differences vs grpc_tools.protoc output:
#   • Messages are Python @dataclass objects, not descriptor-backed objects.
#   • Field names are snake_case (e.g. request_id, alarm_records, cluster_id).
#   • Proto field "_source_id" (field #1) maps to Python "source_id".
#   • The service layer is fully async (grpc.aio).
#   • Serialization uses betterproto.Message.SerializeToString / FromString.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

import betterproto
import grpc
import grpc.aio


# ── Messages ───────────────────────────────────────────────────────────────────

@dataclass
class AlarmRecord(betterproto.Message):
    # Proto field "_source_id" (field #1); leading underscore stripped by betterproto.
    source_id: str = betterproto.string_field(1)
    managed_objects: str = betterproto.string_field(2)
    alarm_type: str = betterproto.string_field(3)
    probable_cause: str = betterproto.string_field(4)
    perceived_severity: str = betterproto.string_field(5)
    state: str = betterproto.string_field(6)
    created_at: str = betterproto.string_field(7)
    closed_at: str = betterproto.string_field(8)


@dataclass
class AnalyzeOnlineAlarmClusterRequest(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    system: str = betterproto.string_field(2)
    alarm_records: List[AlarmRecord] = betterproto.message_field(3)


@dataclass
class OnlineAlarmClusterResult(betterproto.Message):
    # Proto field "_source_id" (field #1)
    source_id: str = betterproto.string_field(1)
    cluster_id: int = betterproto.int32_field(2)
    confidence: float = betterproto.float_field(3)


@dataclass
class OnlineAlarmClusterReport(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    report_type: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    message: str = betterproto.string_field(4)
    results: List[OnlineAlarmClusterResult] = betterproto.message_field(5)


# ── Client Stub ────────────────────────────────────────────────────────────────

class AlarmClusteringServiceStub(betterproto.ServiceStub):
    """Async client stub for AlarmClusteringService."""

    async def analyze_online_alarm_cluster(
        self,
        request: AnalyzeOnlineAlarmClusterRequest,
        *,
        timeout: Optional[float] = None,
        deadline: Optional[betterproto.Deadline] = None,
        metadata: Optional[betterproto.MetadataLike] = None,
    ) -> OnlineAlarmClusterReport:
        return await self._unary_unary(
            "/alarm_clustering.AlarmClusteringService/AnalyzeOnlineAlarmCluster",
            request,
            OnlineAlarmClusterReport,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


# ── Server Base ────────────────────────────────────────────────────────────────

class AlarmClusteringServiceBase(betterproto.ServiceBase):
    """
    Base class for the AlarmClusteringService gRPC server implementation.

    Subclass this and override analyze_online_alarm_cluster().
    Register with a grpc.aio.Server via __mapping__().
    """

    async def analyze_online_alarm_cluster(
        self,
        request: AnalyzeOnlineAlarmClusterRequest,
    ) -> OnlineAlarmClusterReport:
        raise grpc.RpcError(grpc.StatusCode.UNIMPLEMENTED)

    async def __rpc_analyze_online_alarm_cluster(
        self,
        stream: grpc.aio.ServicerContext,
    ) -> None:
        request = await stream.recv_message()
        response = await self.analyze_online_alarm_cluster(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpc.RpcMethodHandler]:
        return {
            "/alarm_clustering.AlarmClusteringService/AnalyzeOnlineAlarmCluster": (
                grpc.unary_unary_rpc_method_handler(
                    self.__rpc_analyze_online_alarm_cluster,
                    request_deserializer=AnalyzeOnlineAlarmClusterRequest.FromString,
                    response_serializer=OnlineAlarmClusterReport.SerializeToString,
                )
            ),
        }
