# grpcio_support.py — hand-written grpcio adapter for BetterProto messages.
#
# NOT generated by betterproto — do not overwrite when regenerating.
#
# BetterProto's ServiceBase targets grpclib, not grpcio.
# This module provides the grpcio equivalent:
#   - AlarmClusteringServiceBase  : async base class for the grpcio server
#   - add_to_server()             : registers the servicer with a grpc.aio.Server
from __future__ import annotations

import grpc

from .engine import (
    AnalyzeOnlineAlarmClusterRequest,
    OnlineAlarmClusterReport,
)


class AlarmClusteringServiceBase:
    """
    Async base class for the grpcio implementation of AlarmClusteringService.

    Subclass this, override analyze_online_alarm_cluster(), then register
    with a grpc.aio.Server via add_to_server().
    """

    async def analyze_online_alarm_cluster(
        self,
        request: AnalyzeOnlineAlarmClusterRequest,
        context: grpc.aio.ServicerContext,
    ) -> OnlineAlarmClusterReport:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("analyze_online_alarm_cluster not implemented")


def add_to_server(servicer: AlarmClusteringServiceBase, server: grpc.aio.Server) -> None:
    """Register servicer handlers with a grpc.aio.Server."""
    handlers = {
        "AnalyzeOnlineAlarmCluster": grpc.unary_unary_rpc_method_handler(
            servicer.analyze_online_alarm_cluster,
            request_deserializer=AnalyzeOnlineAlarmClusterRequest.FromString,
            response_serializer=bytes,  # betterproto.Message.__bytes__ → protobuf wire format
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "alarm_clustering.AlarmClusteringService", handlers
    )
    server.add_generic_rpc_handlers([generic_handler])
