# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x10\x61larm_clustering\"\xb7\x01\n\x0b\x41larmRecord\x12\x12\n\n_source_id\x18\x01 \x01(\t\x12\x17\n\x0fmanaged_objects\x18\x02 \x01(\t\x12\x11\n\talarmType\x18\x03 \x01(\t\x12\x16\n\x0eprobable_cause\x18\x04 \x01(\t\x12\x1a\n\x12perceived_severity\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x11\n\tclosed_at\x18\x08 \x01(\t\"z\n AnalyzeOnlineAlarmClusterRequest\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t\x12\x33\n\x0c\x61larmRecords\x18\x03 \x03(\x0b\x32\x1d.alarm_clustering.AlarmRecord\"U\n\x18OnlineAlarmClusterResult\x12\x12\n\n_source_id\x18\x01 \x01(\t\x12\x11\n\tclusterId\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\x9f\x01\n\x18OnlineAlarmClusterReport\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x12\n\nreportType\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12;\n\x07results\x18\x05 \x03(\x0b\x32*.alarm_clustering.OnlineAlarmClusterResult2\x95\x01\n\x16\x41larmClusteringService\x12{\n\x19\x41nalyzeOnlineAlarmCluster\x12\x32.alarm_clustering.AnalyzeOnlineAlarmClusterRequest\x1a*.alarm_clustering.OnlineAlarmClusterReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALARMRECORD']._serialized_start=35
  _globals['_ALARMRECORD']._serialized_end=218
  _globals['_ANALYZEONLINEALARMCLUSTERREQUEST']._serialized_start=220
  _globals['_ANALYZEONLINEALARMCLUSTERREQUEST']._serialized_end=342
  _globals['_ONLINEALARMCLUSTERRESULT']._serialized_start=344
  _globals['_ONLINEALARMCLUSTERRESULT']._serialized_end=429
  _globals['_ONLINEALARMCLUSTERREPORT']._serialized_start=432
  _globals['_ONLINEALARMCLUSTERREPORT']._serialized_end=591
  _globals['_ALARMCLUSTERINGSERVICE']._serialized_start=594
  _globals['_ALARMCLUSTERINGSERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
