# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from proto import engine_pb2 as engine__pb2
except ImportError:
    import engine_pb2 as engine__pb2  # fallback when proto/ is on sys.path directly

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlarmClusteringServiceStub(object):
    """── Service ────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeOnlineAlarmCluster = channel.unary_unary(
                '/alarm_clustering.AlarmClusteringService/AnalyzeOnlineAlarmCluster',
                request_serializer=engine__pb2.AnalyzeOnlineAlarmClusterRequest.SerializeToString,
                response_deserializer=engine__pb2.OnlineAlarmClusterReport.FromString,
                _registered_method=True)


class AlarmClusteringServiceServicer(object):
    """── Service ────────────────────────────────────────────────────────────────────
    """

    def AnalyzeOnlineAlarmCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlarmClusteringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeOnlineAlarmCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeOnlineAlarmCluster,
                    request_deserializer=engine__pb2.AnalyzeOnlineAlarmClusterRequest.FromString,
                    response_serializer=engine__pb2.OnlineAlarmClusterReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alarm_clustering.AlarmClusteringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alarm_clustering.AlarmClusteringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlarmClusteringService(object):
    """── Service ────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def AnalyzeOnlineAlarmCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alarm_clustering.AlarmClusteringService/AnalyzeOnlineAlarmCluster',
            engine__pb2.AnalyzeOnlineAlarmClusterRequest.SerializeToString,
            engine__pb2.OnlineAlarmClusterReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
